#!/bin/sh

#SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
GEOGIT_MSG=$(curl geo-git.herokuapp.com/locate/geogit)

grep -qs "^$GEOGIT_MSG" "$1" || echo "$GEOGIT_MSG" >> "$1"