#!/bin/sh

GEOGIT_MSG=$(curl -s geo-git.herokuapp.com/locate/geogit)

#grep -qs "^$GEOGIT_MSG" "$1" || echo "\n\n\n$GEOGIT_MSG" >> "$1"
grep -qs "^$GEOGIT_MSG" "$1" || echo "-----------------\n$GEOGIT_MSG" >> "$1"